### ISSUE TITLE
Rendering issues when providing HTML encodable symbols

### ISSUE THREAD

**Issue by djesionek** [vspaceone/LabelGenerator#1]
Example: /instructed/test%25%26%25%26.png
Result:
![image](https://user-images.githubusercontent.com/20115874/113435838-e42dd400-93e3-11eb-994a-4c8fc89d8663.png)

Also:  /instructed/test%2F.png
This breaks the request, probably the forward slash is interpreted in a wrong way.

**Comment by noppelmax** [comment]
Thanks! Fixed in commit 8277ba733be64adc6bd07c0d7b7fbfa0db9b5735

-> v0.0.2
